//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rodstvenik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string Имя { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Mail { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public Nullable<int> ID_role { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
